import Head from 'next/head'
import { Inter } from 'next/font/google'
import MainLayout from '@/components/MainLayout'
// components 
import AllBooks from '@/components/AllBooks'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BookShare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h1 className="h1-heading"> Recently Added Books </h1>
        <AllBooks />
      </MainLayout>
    </>
  )
}
